export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_CART = 'GET_CART'
export const GET_ORDERS = 'GET_ORDERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_ERRORS = 'GET_ERRORS'